title: Yuki Wu
description: My Personal Blog
author: Yuki Wu
logo: /static/img/avatar.jpg
github: https://github.com/wuyuki
about: Share ideas, share life ^_^
keyword: "yuki, wuyuki, yukiwu, blog, data analysis" 

baseurl: ""
url: "https://wuyuki.github.io/"

allowsearch: true

# disqus_shortname: aboutyuki
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000

# SNS settings
github_username: wuyuki

enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
